### ISSUE TITLE
Error

### ISSUE THREAD

**Issue by CaSuS55** [yaldabaoth444/Asphalt9win#1]
I start the bot but I get an error. can you help me?

Error
check Free pack
Error: Primitive «interface.plus» not found

**Comment by yaldabaoth444** [comment]
![PLUS {LOC_TR25, TLR_0 8}](https://user-images.githubusercontent.com/25618671/184593685-47cc3158-477e-449b-8596-547f9b21ef68.png)

**Comment by yaldabaoth444** [comment]
path \Source\Interface\PLUS {LOC_TR25, TLR_0.8}.png

**Comment by yaldabaoth444** [comment]
Hi, sorry for lag
